# Generated by Django 5.1.1 on 2024-09-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crudapp", "0002_remove_note_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="media/"),
        ),
    ]
